import ctypes
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request
import webbrowser

from PySide6.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout,
                              QHBoxLayout, QLabel, QPushButton, QCheckBox, QScrollArea,
                              QFrame, QProgressBar, QMessageBox, QSizePolicy, QLineEdit)
from PySide6.QtCore import Qt, QThread, Signal, QTimer
from PySide6.QtGui import QFont, QIcon

try:
    from _build import VERSION, REPO, BRANCH  # generated by the release workflow
except ImportError:
    VERSION, REPO, BRANCH = "dev", "", ""

APP_DIR = os.path.dirname(os.path.abspath(__file__))
CATALOG_PATH = "app/packages.json"  # location inside the repo, used to fetch the latest app list
PACKAGE_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
CHOCO_SUCCESS_CODES = {0, 1641, 3010}  # 1641/3010: installed, reboot required
CHOCO_INSTALL_SCRIPT = (
    "Set-ExecutionPolicy Bypass -Scope Process -Force; "
    "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; "
    "iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
)


def is_admin():
    """Check if the current process has admin privileges"""
    try:
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except (AttributeError, OSError):
        return False


def run_as_admin():
    """Relaunch this program elevated. Returns True if the UAC prompt was accepted."""
    args = sys.argv[1:] if getattr(sys, "frozen", False) else [os.path.abspath(__file__), *sys.argv[1:]]
    # ShellExecuteW returns a value > 32 on success; declining UAC returns 5
    return ctypes.windll.shell32.ShellExecuteW(
        None, "runas", sys.executable, subprocess.list2cmdline(args), None, 1) > 32


def find_choco():
    """Path to choco.exe, or None. Checks the install dir too, since PATH isn't refreshed after a fresh install."""
    candidates = [shutil.which("choco")]
    for root in (os.environ.get("ChocolateyInstall"),
                 os.path.join(os.environ.get("ProgramData", r"C:\ProgramData"), "chocolatey")):
        if root:
            candidates.append(os.path.join(root, "bin", "choco.exe"))
    return next((path for path in candidates if path and os.path.isfile(path)), None)


def run_hidden(cmd):
    """Run a console program without flashing a console window."""
    return subprocess.run(cmd, stdin=subprocess.DEVNULL, capture_output=True, text=True, errors="replace",
                          creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))


def choco_install(choco, package):
    """Install one package and return choco's exit code."""
    # The id becomes a command-line argument: reject anything that could be read as an option
    if not isinstance(package, str) or not PACKAGE_ID.fullmatch(package):
        raise ValueError(f"invalid package id: {package!r}")
    return run_hidden([choco, "install", package, "-y", "--no-progress"]).returncode


def validate_catalog(catalog):
    """Return catalog if it is {category: {app name: {"package": id, ...}}}, else raise ValueError."""
    if not isinstance(catalog, dict) or not catalog:
        raise ValueError("catalog is empty")
    for category, apps in catalog.items():
        if not isinstance(apps, dict):
            raise ValueError(f"{category}: expected a list of apps")
        for name, app in apps.items():
            if not (isinstance(app, dict)
                    and isinstance(app.get("package"), str) and PACKAGE_ID.fullmatch(app["package"])
                    and isinstance(app.get("description", ""), str)
                    and isinstance(app.get("icon", ""), str)
                    and isinstance(app.get("size", 0), (int, float))):
                raise ValueError(f"{category}/{name}: invalid entry")
    return catalog


def load_catalog():
    """The latest app list from the repo this build came from, or the copy bundled with the app."""
    if REPO:
        url = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/{CATALOG_PATH}"
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                return validate_catalog(json.load(response))
        except Exception:
            pass  # offline, repo moved or bad data: use the bundled copy
    with open(os.path.join(APP_DIR, "packages.json"), encoding="utf-8") as f:
        return validate_catalog(json.load(f))


class CustomTitleBar(QFrame):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent_window = parent
        self.setFixedHeight(45)
        self.setup_ui()

    def setup_ui(self):
        self.setStyleSheet("""
            QFrame {
                background-color: #161b22;
                border: none;
            }
        """)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(20, 12, 15, 12)
        layout.setSpacing(12)

        title_label = QLabel("Spaller")
        title_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
        title_label.setStyleSheet("color: #58a6ff; border: none;")
        layout.addWidget(title_label)

        subtitle_label = QLabel("Chocolatey Package Installer")
        subtitle_label.setFont(QFont("Segoe UI", 9))
        subtitle_label.setStyleSheet("color: #8b949e; border: none;")
        layout.addWidget(subtitle_label)

        layout.addStretch()

        controls_layout = QHBoxLayout()
        controls_layout.setSpacing(6)

        self.minimize_btn = QPushButton("−")
        self.minimize_btn.setFixedSize(30, 22)
        self.minimize_btn.setFont(QFont("Segoe UI", 12, QFont.Bold))
        self.minimize_btn.setStyleSheet("""
            QPushButton {
                background-color: #21262d;
                color: #f0f6fc;
                border: none;
                border-radius: 3px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #30363d;
            }
            QPushButton:pressed {
                background-color: #1c2128;
            }
        """)
        self.minimize_btn.clicked.connect(self.parent_window.showMinimized)
        controls_layout.addWidget(self.minimize_btn)

        self.close_btn = QPushButton("×")
        self.close_btn.setFixedSize(30, 22)
        self.close_btn.setFont(QFont("Segoe UI", 14, QFont.Bold))
        self.close_btn.setStyleSheet("""
            QPushButton {
                background-color: #da3633;
                color: #ffffff;
                border: none;
                border-radius: 3px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #f85149;
            }
            QPushButton:pressed {
                background-color: #b91c1c;
            }
        """)
        self.close_btn.clicked.connect(self.parent_window.close)
        controls_layout.addWidget(self.close_btn)

        layout.addLayout(controls_layout)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            # Native move: keeps Windows snap and multi-monitor DPI handling
            self.window().windowHandle().startSystemMove()
            event.accept()


class StyledButton(QPushButton):
    STYLES = {
        "primary": {"bg": "#238636", "hover": "#2ea043", "text": "#ffffff"},
        "secondary": {"bg": "#21262d", "hover": "#30363d", "text": "#f0f6fc"},
        "accent": {"bg": "#1f6feb", "hover": "#388bfd", "text": "#ffffff"},
    }

    def __init__(self, text, style="primary", parent=None):
        super().__init__(text, parent)
        style = self.STYLES.get(style, self.STYLES["primary"])
        self.setCursor(Qt.PointingHandCursor)
        self.setStyleSheet(f"""
            QPushButton {{
                background-color: {style['bg']};
                color: {style['text']};
                border: none;
                border-radius: 5px;
                padding: 8px 16px;
                font-family: 'Segoe UI';
                font-size: 10px;
                font-weight: bold;
            }}
            QPushButton:hover {{
                background-color: {style['hover']};
            }}
            QPushButton:pressed {{
                background-color: {style['bg']};
            }}
            QPushButton:disabled {{
                background-color: #21262d;
                color: #484f58;
            }}
        """)


class ModernCheckBox(QFrame):
    toggled = Signal(bool)

    def __init__(self, app, parent=None):
        super().__init__(parent)
        self.app = app
        self.setup_ui()
        self.setup_style()

    def setup_ui(self):
        self.setMinimumHeight(70)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.setCursor(Qt.PointingHandCursor)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(18, 12, 18, 12)
        layout.setSpacing(12)

        icon_label = QLabel(self.app["icon"])
        icon_label.setFont(QFont("Segoe UI", 16))
        icon_label.setFixedSize(32, 32)
        icon_label.setAlignment(Qt.AlignCenter)
        icon_label.setStyleSheet("""
            QLabel {
                background-color: #21262d;
                border-radius: 6px;
                color: #58a6ff;
                border: none;
            }
        """)

        layout.addWidget(icon_label)

        self.checkbox = QCheckBox()
        self.checkbox.setFixedSize(20, 20)
        self.checkbox.toggled.connect(self.toggled)
        layout.addWidget(self.checkbox)

        text_layout = QVBoxLayout()
        text_layout.setSpacing(3)

        title_layout = QHBoxLayout()
        title_layout.setSpacing(8)

        title_label = QLabel(self.app["name"])
        title_label.setFont(QFont("Segoe UI", 11, QFont.Bold))
        title_label.setStyleSheet("color: #f0f6fc; border: none;")
        title_label.setWordWrap(True)
        title_layout.addWidget(title_label)

        info_btn = QPushButton("ℹ")
        info_btn.setFixedSize(18, 18)
        info_btn.setFont(QFont("Segoe UI", 10))
        info_btn.setStyleSheet("""
            QPushButton {
                background-color: #30363d;
                color: #58a6ff;
                border: none;
                border-radius: 9px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #58a6ff;
                color: #ffffff;
            }
        """)
        info_btn.setToolTip(f"Chocolatey package: {self.app['package']}\nSize: ~{self.app['size']} MB\n\nClick for more details")
        info_btn.clicked.connect(self.show_app_info)
        title_layout.addWidget(info_btn)
        title_layout.addStretch()

        text_layout.addLayout(title_layout)

        if self.app["description"]:
            desc_label = QLabel(self.app["description"])
            desc_label.setFont(QFont("Segoe UI", 9))
            desc_label.setStyleSheet("color: #8b949e; border: none;")
            desc_label.setWordWrap(True)
            desc_label.setMaximumHeight(40)
            text_layout.addWidget(desc_label)

        layout.addLayout(text_layout)

        size_label = QLabel(f"{self.app['size']} MB")
        size_label.setFont(QFont("Segoe UI", 9))
        size_label.setStyleSheet("color: #8b949e; border: none;")
        size_label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        layout.addWidget(size_label)

    def show_app_info(self):
        QMessageBox.information(self, f"{self.app['name']} - Information",
                                f"Application: {self.app['name']}\n"
                                f"Description: {self.app['description']}\n"
                                f"Chocolatey package: {self.app['package']}\n"
                                f"Version: Latest available\n"
                                f"Size: ~{self.app['size']} MB\n\n"
                                f"https://community.chocolatey.org/packages/{self.app['package']}")

    def setup_style(self):
        self.checkbox.setStyleSheet("""
            QCheckBox {
                spacing: 0px;
            }
            QCheckBox::indicator {
                width: 18px;
                height: 18px;
                border-radius: 3px;
                border: 2px solid #30363d;
                background-color: #161b22;
            }
            QCheckBox::indicator:hover {
                border-color: #58a6ff;
                background-color: #1c2128;
            }
            QCheckBox::indicator:checked {
                background-color: #238636;
                border-color: #238636;
            }
        """)

        self.setStyleSheet("""
            QFrame {
                background-color: #161b22;
                border: 1px solid #21262d;
                border-radius: 5px;
                margin: 1px;
            }
        """)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.checkbox.toggle()
        super().mousePressEvent(event)

    def isChecked(self):
        return self.checkbox.isChecked()

    def setChecked(self, checked):
        self.checkbox.setChecked(checked)


class CategoryButton(QPushButton):
    def __init__(self, text, count=0, parent=None):
        super().__init__(parent)
        self.category_text = text
        self.is_active = False
        self.setFixedHeight(42)
        self.setFont(QFont("Segoe UI", 10))
        self.setCursor(Qt.PointingHandCursor)
        self.set_count(count)
        self.update_style()

    def update_style(self):
        if self.is_active:
            self.setStyleSheet("""
                QPushButton {
                    background-color: #21262d;
                    color: #f0f6fc;
                    border: none;
                    border-left: 3px solid #58a6ff;
                    border-radius: 0px;
                    padding: 10px 16px;
                    text-align: left;
                    font-weight: bold;
                }
                QPushButton:hover {
                    background-color: #30363d;
                }
            """)
        else:
            self.setStyleSheet("""
                QPushButton {
                    background-color: #161b22;
                    color: #7d8590;
                    border: none;
                    border-left: 3px solid transparent;
                    border-radius: 0px;
                    padding: 10px 16px;
                    text-align: left;
                    font-weight: normal;
                }
                QPushButton:hover {
                    background-color: #21262d;
                    color: #f0f6fc;
                }
            """)

    def set_active(self, active):
        self.is_active = active
        self.update_style()

    def set_count(self, count):
        display_text = f"{self.category_text} ({count})"
        if len(display_text) > 20:
            display_text = f"{self.category_text[:12]}... ({count})"
        self.setText(display_text)


class CatalogLoader(QThread):
    loaded = Signal(object)
    failed = Signal(str)

    def run(self):
        try:
            self.loaded.emit(load_catalog())
        except Exception as e:
            self.failed.emit(str(e))


class ChocolateySetupThread(QThread):
    """Runs the official Chocolatey installer; read `message` after `finished`."""
    message = ""

    def run(self):
        try:
            result = run_hidden(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                                 "-Command", CHOCO_INSTALL_SCRIPT])
            output = (result.stderr or result.stdout).strip()
            self.message = output.splitlines()[-1] if output else f"exit code {result.returncode}"
        except OSError as e:
            self.message = str(e)


class InstallationThread(QThread):
    """Installs apps one by one; read the result attributes after `finished`."""
    progress_updated = Signal(int, int, str)  # apps done, total, current app

    def __init__(self, choco, apps):
        super().__init__()
        self.choco = choco
        self.apps = apps  # [(app_id, name, package)]
        self.installed = []  # app ids
        self.failed = []  # human-readable reasons
        self.reboot_required = False
        self.cancelled = False

    def run(self):
        for i, (app_id, name, package) in enumerate(self.apps):
            if self.isInterruptionRequested():
                self.cancelled = True
                break
            self.progress_updated.emit(i, len(self.apps), name)
            try:
                code = choco_install(self.choco, package)
            except (OSError, ValueError) as e:
                self.failed.append(f"{name}: {e}")
                continue
            if code in CHOCO_SUCCESS_CODES:
                self.installed.append(app_id)
                self.reboot_required |= code != 0
            else:
                self.failed.append(f"{name} (exit code {code})")


class SpallerMainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.apps = {}  # app_id -> app info
        self.selected = set()  # selected app ids
        self.app_checkboxes = {}  # app ids currently on screen -> checkbox
        self.category_buttons = {}
        self.current_category = None
        self.choco = None
        self.choco_setup = None
        self.installer = None
        self.installing = False

        self.setup_ui()

        self.loader = CatalogLoader()
        self.loader.loaded.connect(self.on_catalog_loaded)
        self.loader.failed.connect(self.on_catalog_error)
        self.loader.start()
        QTimer.singleShot(0, self.check_chocolatey)

    def setup_ui(self):
        # MinimizeButtonHint lets the taskbar button minimize a frameless window
        self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinimizeButtonHint)
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.setWindowTitle("Spaller")

        self.setFixedSize(1000, 650)

        screen = QApplication.primaryScreen().availableGeometry()
        self.move(screen.center() - self.rect().center())

        main_container = QFrame()
        main_container.setStyleSheet("""
            QFrame {
                background-color: #0d1117;
                border-radius: 6px;
                border: 1px solid #21262d;
            }
        """)
        self.setCentralWidget(main_container)

        main_layout = QVBoxLayout(main_container)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)

        self.title_bar = CustomTitleBar(self)
        main_layout.addWidget(self.title_bar)

        self.create_header(main_layout)

        content_layout = QHBoxLayout()
        content_layout.setContentsMargins(0, 0, 0, 0)
        content_layout.setSpacing(0)

        self.create_sidebar(content_layout)
        self.create_main_content(content_layout)

        main_layout.addLayout(content_layout)

        self.create_bottom_section(main_layout)
        self.create_footer(main_layout)

    def create_header(self, layout):
        header = QFrame()
        header.setFixedHeight(75)
        header.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #161b22, stop:1 #1c2128);
                border: none;
                border-bottom: 1px solid #21262d;
            }
        """)

        header_layout = QHBoxLayout(header)
        header_layout.setContentsMargins(25, 15, 25, 15)
        header_layout.setSpacing(20)

        # Chocolatey status
        choco_layout = QVBoxLayout()
        choco_layout.setSpacing(3)

        choco_label = QLabel("📦 Package Manager:")
        choco_label.setFont(QFont("Segoe UI", 8))
        choco_label.setStyleSheet("color: #8b949e; border: none;")
        choco_layout.addWidget(choco_label)

        self.choco_status = QLabel("Chocolatey (Checking...)")
        self.choco_status.setFont(QFont("Segoe UI", 9, QFont.Bold))
        self.choco_status.setStyleSheet("color: #f0f6fc; border: none;")
        choco_layout.addWidget(self.choco_status)

        header_layout.addLayout(choco_layout)

        search_layout = QVBoxLayout()
        search_layout.setSpacing(3)

        search_label = QLabel("🔍 Search Apps:")
        search_label.setFont(QFont("Segoe UI", 8))
        search_label.setStyleSheet("color: #8b949e; border: none;")
        search_layout.addWidget(search_label)

        self.search_bar = QLineEdit()
        self.search_bar.setPlaceholderText("Search applications...")
        self.search_bar.setClearButtonEnabled(True)
        self.search_bar.setFixedWidth(200)
        self.search_bar.setStyleSheet("""
            QLineEdit {
                background-color: #21262d;
                border: 1px solid #30363d;
                border-radius: 4px;
                padding: 6px 10px;
                color: #f0f6fc;
                font-size: 9px;
            }
            QLineEdit:focus {
                border-color: #58a6ff;
            }
        """)
        self.search_bar.textChanged.connect(self.filter_apps)
        search_layout.addWidget(self.search_bar)

        header_layout.addLayout(search_layout)
        header_layout.addStretch()

        self.select_all_btn = StyledButton("Select All", "accent")
        self.select_all_btn.setFixedSize(85, 30)
        self.select_all_btn.setToolTip("Select or deselect every app in every category")
        self.select_all_btn.clicked.connect(self.toggle_select_all)
        header_layout.addWidget(self.select_all_btn)

        layout.addWidget(header)

    def create_sidebar(self, layout):
        sidebar = QFrame()
        sidebar.setFixedWidth(200)
        sidebar.setStyleSheet("""
            QFrame {
                background-color: #161b22;
                border: none;
                border-right: 1px solid #21262d;
            }
        """)

        sidebar_layout = QVBoxLayout(sidebar)
        sidebar_layout.setContentsMargins(0, 15, 0, 0)
        sidebar_layout.setSpacing(0)

        categories_label = QLabel("Categories")
        categories_label.setFont(QFont("Segoe UI", 11, QFont.Bold))
        categories_label.setStyleSheet("color: #f0f6fc; padding: 0 16px 12px 16px; border: none;")
        sidebar_layout.addWidget(categories_label)

        self.categories_container = QVBoxLayout()
        self.categories_container.setSpacing(1)
        sidebar_layout.addLayout(self.categories_container)

        sidebar_layout.addStretch()
        layout.addWidget(sidebar)

    def create_main_content(self, layout):
        content_frame = QFrame()
        content_frame.setStyleSheet("""
            QFrame {
                background-color: #0d1117;
                border: none;
            }
        """)

        content_layout = QVBoxLayout(content_frame)
        content_layout.setContentsMargins(20, 15, 15, 15)
        content_layout.setSpacing(12)

        header_layout = QHBoxLayout()
        header_layout.setSpacing(12)

        title_layout = QVBoxLayout()
        title_layout.setSpacing(3)

        self.category_title = QLabel("Loading applications...")
        self.category_title.setFont(QFont("Segoe UI", 16, QFont.Bold))
        self.category_title.setStyleSheet("color: #f0f6fc; border: none;")
        self.category_title.setWordWrap(True)
        title_layout.addWidget(self.category_title)

        self.category_count = QLabel("")
        self.category_count.setFont(QFont("Segoe UI", 10))
        self.category_count.setStyleSheet("color: #8b949e; border: none;")
        title_layout.addWidget(self.category_count)

        header_layout.addLayout(title_layout)
        header_layout.addStretch()

        self.select_category_btn = StyledButton("Select All", "secondary")
        self.select_category_btn.setFixedSize(85, 28)
        self.select_category_btn.setToolTip("Select or deselect the apps listed below")
        self.select_category_btn.clicked.connect(self.toggle_select_visible)
        header_layout.addWidget(self.select_category_btn)

        content_layout.addLayout(header_layout)

        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        scroll_area.setStyleSheet("""
            QScrollArea {
                border: none;
                background-color: transparent;
                background: transparent;
            }
            QScrollBar:vertical {
                background-color: #21262d;
                width: 16px;
                border-radius: 8px;
                border: none;
                margin: 3px;
            }
            QScrollBar::handle:vertical {
                background-color: #58a6ff;
                border-radius: 8px;
                min-height: 25px;
                border: none;
                margin: 2px;
            }
            QScrollBar::handle:vertical:hover {
                background-color: #388bfd;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                border: none;
                background: none;
            }
        """)

        self.scroll_widget = QWidget()
        self.scroll_widget.setStyleSheet("""
            QWidget {
                background-color: transparent;
                background: transparent;
            }
        """)
        self.scroll_layout = QVBoxLayout(self.scroll_widget)
        self.scroll_layout.setContentsMargins(0, 0, 8, 0)
        self.scroll_layout.setSpacing(6)

        scroll_area.setWidget(self.scroll_widget)
        content_layout.addWidget(scroll_area)

        layout.addWidget(content_frame)

    def create_bottom_section(self, layout):
        bottom_frame = QFrame()
        bottom_frame.setFixedHeight(100)
        bottom_frame.setStyleSheet("""
            QFrame {
                background-color: #0d1117;
                border: none;
                border-top: 1px solid #21262d;
            }
        """)

        bottom_layout = QVBoxLayout(bottom_frame)
        bottom_layout.setContentsMargins(25, 15, 25, 15)
        bottom_layout.setSpacing(8)

        # Top row with selection info and install button
        top_row_layout = QHBoxLayout()
        top_row_layout.setSpacing(20)

        selection_info_layout = QVBoxLayout()
        selection_info_layout.setSpacing(2)

        self.selected_count_label = QLabel("No applications selected")
        self.selected_count_label.setFont(QFont("Segoe UI", 11, QFont.Bold))
        self.selected_count_label.setStyleSheet("color: #8b949e; border: none;")
        selection_info_layout.addWidget(self.selected_count_label)

        self.size_info_label = QLabel("")
        self.size_info_label.setFont(QFont("Segoe UI", 9))
        self.size_info_label.setStyleSheet("color: #6e7681; border: none;")
        selection_info_layout.addWidget(self.size_info_label)

        top_row_layout.addLayout(selection_info_layout)
        top_row_layout.addStretch(1)

        self.install_btn = StyledButton("📦 Install Selected", "primary")
        self.install_btn.setFixedSize(160, 35)
        self.install_btn.setFont(QFont("Segoe UI", 10, QFont.Bold))
        self.install_btn.clicked.connect(self.start_installation)
        self.install_btn.setEnabled(False)
        top_row_layout.addWidget(self.install_btn)

        bottom_layout.addLayout(top_row_layout)

        # Progress row
        progress_layout = QHBoxLayout()
        progress_layout.setSpacing(15)

        self.status_label = QLabel("Checking system requirements...")
        self.status_label.setFont(QFont("Segoe UI", 9, QFont.Bold))
        self.status_label.setStyleSheet("color: #f0f6fc; border: none;")
        self.status_label.setFixedWidth(280)
        progress_layout.addWidget(self.status_label)

        progress_container = QWidget()
        progress_container.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        progress_container.setFixedHeight(20)
        progress_container_layout = QVBoxLayout(progress_container)
        progress_container_layout.setContentsMargins(0, 4, 0, 4)
        progress_container_layout.setSpacing(0)

        self.progress_bar = QProgressBar()
        self.progress_bar.setFixedHeight(12)
        self.progress_bar.setStyleSheet("""
            QProgressBar {
                border: none;
                border-radius: 6px;
                background-color: #21262d;
                text-align: center;
                color: #f0f6fc;
                font-size: 8px;
                font-weight: bold;
            }
            QProgressBar::chunk {
                border-radius: 6px;
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                    stop:0 #58a6ff, stop:1 #388bfd);
            }
        """)
        progress_container_layout.addWidget(self.progress_bar, 0, Qt.AlignVCenter)
        progress_layout.addWidget(progress_container, 1)

        self.cancel_btn = QPushButton("Cancel")
        self.cancel_btn.setFixedSize(60, 24)
        self.cancel_btn.setFont(QFont("Segoe UI", 8))
        self.cancel_btn.setToolTip("Stop after the app that is installing now")
        self.cancel_btn.setStyleSheet("""
            QPushButton {
                background-color: #21262d;
                color: #f0f6fc;
                border: 1px solid #30363d;
                border-radius: 4px;
                padding: 4px 8px;
            }
            QPushButton:hover {
                background-color: #30363d;
                border-color: #58a6ff;
            }
            QPushButton:disabled {
                background-color: #161b22;
                color: #484f58;
                border-color: #21262d;
            }
        """)
        self.cancel_btn.setEnabled(False)
        self.cancel_btn.clicked.connect(self.cancel_installation)
        progress_layout.addWidget(self.cancel_btn)

        bottom_layout.addLayout(progress_layout)

        layout.addWidget(bottom_frame)

    def create_footer(self, layout):
        footer = QFrame()
        footer.setFixedHeight(28)
        footer.setStyleSheet("""
            QFrame {
                background-color: #161b22;
                border: none;
            }
        """)

        footer_layout = QHBoxLayout(footer)
        footer_layout.setContentsMargins(25, 8, 25, 8)

        copyright_text = f'© Ice - <a style="color: #58a6ff;" href="https://github.com/{REPO}">github.com/{REPO}</a>' if REPO else "© Ice"
        copyright_label = QLabel(copyright_text)
        copyright_label.setOpenExternalLinks(True)
        copyright_label.setFont(QFont("Segoe UI", 8))
        copyright_label.setStyleSheet("color: #8b949e; border: none;")
        footer_layout.addWidget(copyright_label)

        footer_layout.addStretch()

        version_label = QLabel(f"{VERSION} - Chocolatey Edition")
        version_label.setFont(QFont("Segoe UI", 8))
        version_label.setStyleSheet("color: #8b949e; border: none;")
        footer_layout.addWidget(version_label)

        layout.addWidget(footer)

    def set_status(self, text, color="#f0f6fc"):
        self.status_label.setText(text)
        self.status_label.setToolTip(text)
        self.status_label.setStyleSheet(f"color: {color}; border: none;")

    def set_choco_status(self, text, color):
        self.choco_status.setText(text)
        self.choco_status.setStyleSheet(f"color: {color}; border: none;")

    def check_chocolatey(self):
        """Find Chocolatey, offering to install it when missing."""
        if self.choco_setup and self.choco_setup.isRunning():
            return
        self.choco = find_choco()
        if self.choco:
            self.set_choco_status("Chocolatey (Ready)", "#3fb950")
            self.set_status("Ready to install packages")
            return

        self.set_choco_status("Chocolatey (Not installed)", "#f85149")
        self.set_status("Chocolatey is required to install apps", "#f85149")
        reply = QMessageBox.question(
            self,
            "Chocolatey Required",
            "Spaller installs apps with Chocolatey, which isn't installed yet.\n\n"
            "Install Chocolatey now using the official installer from chocolatey.org?"
        )
        if reply == QMessageBox.Yes:
            self.start_chocolatey_setup()

    def start_chocolatey_setup(self):
        self.set_choco_status("Chocolatey (Installing...)", "#fb8500")
        self.set_status("Installing Chocolatey...", "#58a6ff")
        self.choco_setup = ChocolateySetupThread()
        self.choco_setup.finished.connect(self.on_chocolatey_setup_finished)
        self.choco_setup.start()

    def on_chocolatey_setup_finished(self):
        if find_choco():
            self.check_chocolatey()
            return

        self.set_choco_status("Chocolatey (Failed)", "#f85149")
        self.set_status("Chocolatey is required to install apps", "#f85149")
        reply = QMessageBox.critical(
            self,
            "Chocolatey Setup Failed",
            f"Couldn't install Chocolatey:\n{self.choco_setup.message}\n\n"
            "Retry, or press Help to open the manual install guide.",
            QMessageBox.Retry | QMessageBox.Help | QMessageBox.Close
        )
        if reply == QMessageBox.Retry:
            self.start_chocolatey_setup()
        elif reply == QMessageBox.Help:
            webbrowser.open("https://chocolatey.org/install")

    def on_catalog_loaded(self, catalog):
        for category, apps in catalog.items():
            for name, info in apps.items():
                self.apps[f"{category}:{name}"] = {
                    "name": name,
                    "category": category,
                    "package": info["package"],
                    "description": info.get("description", ""),
                    "size": info.get("size", 50),
                    "icon": info.get("icon", "📦"),
                }
            btn = CategoryButton(category, len(apps))
            btn.clicked.connect(lambda checked, cat=category: self.switch_category(cat))
            self.categories_container.addWidget(btn)
            self.category_buttons[category] = btn

        self.switch_category(next(iter(catalog)))

    def on_catalog_error(self, error):
        QMessageBox.critical(self, "Spaller", f"Failed to load the application list:\n{error}")
        self.close()

    def show_apps(self, title, subtitle, app_ids):
        self.category_title.setText(title)
        self.category_count.setText(subtitle)

        self.app_checkboxes.clear()
        while self.scroll_layout.count():
            child = self.scroll_layout.takeAt(0)
            if child.widget():
                child.widget().deleteLater()

        for app_id in app_ids:
            checkbox = ModernCheckBox(self.apps[app_id])
            checkbox.setChecked(app_id in self.selected)
            checkbox.toggled.connect(lambda checked, aid=app_id: self.set_selected([aid], checked))
            self.scroll_layout.addWidget(checkbox)
            self.app_checkboxes[app_id] = checkbox

        if not app_ids:
            empty_label = QLabel("No applications found matching your search.")
            empty_label.setFont(QFont("Segoe UI", 12))
            empty_label.setStyleSheet("color: #8b949e;")
            empty_label.setAlignment(Qt.AlignCenter)
            self.scroll_layout.addWidget(empty_label)

        self.scroll_layout.addStretch()
        self.update_selected_count()

    def switch_category(self, category):
        self.current_category = category
        for cat, btn in self.category_buttons.items():
            btn.set_active(cat == category)

        # Leaving search results: clear the box without re-running the search
        self.search_bar.blockSignals(True)
        self.search_bar.clear()
        self.search_bar.blockSignals(False)

        app_ids = [app_id for app_id, app in self.apps.items() if app["category"] == category]
        self.show_apps(category, f"({len(app_ids)} applications available)", app_ids)

    def filter_apps(self, text):
        """Filter applications across all categories"""
        query = text.strip().lower()
        if not query:
            if self.current_category:
                self.switch_category(self.current_category)
            return

        app_ids = [app_id for app_id, app in self.apps.items()
                   if query in app["name"].lower()
                   or query in app["description"].lower()
                   or query in app["package"].lower()]
        self.show_apps(f"Search Results for '{text.strip()}'", f"({len(app_ids)} applications found)", app_ids)

    def set_selected(self, app_ids, checked):
        for app_id in app_ids:
            if checked:
                self.selected.add(app_id)
            else:
                self.selected.discard(app_id)
            if app_id in self.app_checkboxes:
                self.app_checkboxes[app_id].setChecked(checked)
        self.update_selected_count()

    def toggle_select_all(self):
        self.set_selected(list(self.apps), len(self.selected) < len(self.apps))

    def toggle_select_visible(self):
        visible = list(self.app_checkboxes)
        self.set_selected(visible, not self.selected.issuperset(visible))

    def update_selected_count(self):
        all_selected = bool(self.apps) and len(self.selected) == len(self.apps)
        visible_selected = bool(self.app_checkboxes) and self.selected.issuperset(self.app_checkboxes)
        self.select_all_btn.setText("Deselect All" if all_selected else "Select All")
        self.select_category_btn.setText("Deselect All" if visible_selected else "Select All")

        selected_count = len(self.selected)
        if selected_count == 0:
            self.selected_count_label.setText("No applications selected")
            self.selected_count_label.setStyleSheet("color: #8b949e; border: none; font-style: italic;")
            self.size_info_label.setText("Select apps from the list to install via Chocolatey")
            self.size_info_label.setStyleSheet("color: #6e7681; border: none; font-style: italic;")
        else:
            estimated_size = sum(self.apps[app_id]["size"] for app_id in self.selected)
            size_text = f"{estimated_size} MB" if estimated_size < 1000 else f"{estimated_size / 1000:.1f} GB"
            plural = "s" if selected_count > 1 else ""
            self.selected_count_label.setText(f"{selected_count} application{plural} selected")
            self.size_info_label.setText(f"Estimated download: ~{size_text}")
            self.selected_count_label.setStyleSheet("color: #58a6ff; border: none; font-weight: bold;")
            self.size_info_label.setStyleSheet("color: #3fb950; border: none;")

        if not self.installing:
            self.install_btn.setEnabled(selected_count > 0)
            self.install_btn.setText(
                f"📦 Install {selected_count} App{'s' if selected_count > 1 else ''}" if selected_count else "📦 Install Selected")

    def start_installation(self):
        if self.installing:
            return
        if not self.choco:
            self.check_chocolatey()
            return

        # Catalog order, so dependencies listed first install first
        apps = [(app_id, app["name"], app["package"]) for app_id, app in self.apps.items() if app_id in self.selected]
        if not apps:
            return

        self.installing = True
        self.install_btn.setEnabled(False)
        self.install_btn.setText("Installing...")
        self.cancel_btn.setEnabled(True)
        self.progress_bar.setValue(0)

        self.installer = InstallationThread(self.choco, apps)
        self.installer.progress_updated.connect(self.update_progress)
        self.installer.finished.connect(self.installation_finished)
        self.installer.start()

    def update_progress(self, done, total, app_name):
        self.progress_bar.setValue(done * 100 // total)
        self.install_btn.setText(f"Installing... ({done}/{total})")
        if self.cancel_btn.isEnabled():
            self.set_status(f"Installing {app_name} ({done + 1} of {total})", "#58a6ff")

    def installation_finished(self):
        result = self.installer
        self.installing = False
        self.cancel_btn.setEnabled(False)
        self.progress_bar.setValue(100)

        # Deselect what worked, so pressing Install again retries only the failures
        self.set_selected(result.installed, False)

        summary = f"{len(result.installed)} installed"
        if result.failed:
            summary += f", {len(result.failed)} failed"
        if result.cancelled:
            summary += " (cancelled)"
        self.set_status(summary, "#f85149" if result.failed else "#3fb950")

        lines = [summary + "."]
        if result.reboot_required:
            lines.append("Restart Windows to finish setting up some apps.")
        if result.failed:
            log_path = os.path.join(os.path.dirname(os.path.dirname(self.choco)), "logs", "chocolatey.log")
            lines += ["", "Failed:", *result.failed, "", f"Details: {log_path}"]
        show = QMessageBox.warning if result.failed else QMessageBox.information
        show(self, "Installation Finished", "\n".join(lines))

    def cancel_installation(self):
        """Stop after the current app; killing choco mid-install can leave an app half-installed."""
        if self.installing:
            self.installer.requestInterruption()
            self.cancel_btn.setEnabled(False)
            self.set_status("Cancelling after the current app...", "#fb8500")

    def closeEvent(self, event):
        if self.installing or (self.choco_setup and self.choco_setup.isRunning()):
            QMessageBox.information(self, "Spaller",
                                    "An installation is still running.\n\n"
                                    "Wait for it to finish, or press Cancel to stop after the current app.")
            event.ignore()
            return
        self.loader.wait()  # at most the download timeout
        event.accept()


def main():
    if sys.platform != "win32":
        sys.exit("Spaller only runs on Windows.")

    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    app.setWindowIcon(QIcon(os.path.join(APP_DIR, "icon.ico")))

    # Release builds request admin through their manifest; this covers running from source
    if not is_admin():
        if run_as_admin():
            return 0
        QMessageBox.critical(None, "Spaller",
                             "Spaller needs administrator rights to install software.\n\n"
                             "Right-click Spaller and choose 'Run as administrator'.")
        return 1

    try:
        window = SpallerMainWindow()
    except Exception as e:
        # Windowed builds have no console, so show startup errors instead of exiting silently
        QMessageBox.critical(None, "Startup Error", f"An error occurred during startup:\n{e}")
        return 1
    window.show()
    return app.exec()


if __name__ == "__main__":
    sys.exit(main())
